defaults:
  - scope:
      path: ""
    values:
      layout: "page"

sass:
  load_paths:
    - _sass
    - _sass/node_modules

plugin:
  - jekyll-theme-cs50-1.1.0

markdown: kramdown

collections:
  year:
    output: true
    permalink: /:path
    sort_by: day # Integer
